plot(data5$y, as.numeric(as.character(data5$Sub_metering_1)), ylab = 'Energy sub metering', xlab = "", main = "", type = "l")
lines(data5$y, as.numeric(as.character(data5$Sub_metering_2)), col = "red")
lines(data5$y, as.numeric(as.character(data5$Sub_metering_3)), col = "blue")
legend("topright", lty=c(1,1,1), col = c("black","red","blue"),legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()
